[package]
name = "hydro-flux-splitting"
version = "0.1.0"
authors = ["Jack Hu <zhongth@g.clemson.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
